format = """
[┌](bright-black)\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$cmd_duration\
$line_break\
[└─](bright-black)$character"""

[directory]
format = """[$read_only]($read_only_style)\
[ $path]($style)\
"""
home_symbol = ""
read_only = " 󰍁 "

style = "bold blue"
read_only_style = "bold red"

[character]
success_symbol = "[󰣐](purple)"
error_symbol = "[󱐰](red)"
vimcmd_symbol = "[󱢠](blue)"

[git_branch]
format = "[ $branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "bright-black"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[  $duration]($style) "
style = "bright-black"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
