#! /bin/sh

#
# bspwmrc
#

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot --cursor_name left_ptr
bspc monitor -d 1 2 3 4 5

feh --nofehbg --bg-fill ~/Pictures/wallpapers/ --randomize
rule feh state=floating

dunst &
picom &

rule -a alacritty follow=on focus=on
rule -a librewolf follow=on focus=on

config left_padding 0
config window_gap 5
config split_ratio 0.50

config borderless_monocle false
config gapless_monocle true
config focus_follows_pointer true

bspc config normal_border_color "#161616"
bspc config focused_border_color "#161616"
bspc config border_width 5
pkill borders ; borders &
